# :schema node_modules/wrangler/config-schema.json
name = "tokistack-local-frontend"
compatibility_date = "2026-02-22"
workers_dev = false
preview_urls = false

[assets]
directory = "./dist/browser"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
